// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParentChildAccess.Data;

#nullable disable

namespace ParentChildAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240222180133_InitTableData")]
    partial class InitTableData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParentChildAccess.Model.Node", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NodeId");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            NodeId = 1,
                            Name = "Node 1"
                        },
                        new
                        {
                            NodeId = 2,
                            Name = "Node 2"
                        },
                        new
                        {
                            NodeId = 3,
                            Name = "Node 3"
                        },
                        new
                        {
                            NodeId = 4,
                            Name = "Node 4"
                        },
                        new
                        {
                            NodeId = 5,
                            Name = "Node 5"
                        },
                        new
                        {
                            NodeId = 6,
                            Name = "Node 6"
                        },
                        new
                        {
                            NodeId = 7,
                            Name = "Node 7"
                        },
                        new
                        {
                            NodeId = 8,
                            Name = "Node 8"
                        },
                        new
                        {
                            NodeId = 9,
                            Name = "Node 9"
                        },
                        new
                        {
                            NodeId = 10,
                            Name = "Node 10"
                        },
                        new
                        {
                            NodeId = 11,
                            Name = "Node 11"
                        },
                        new
                        {
                            NodeId = 12,
                            Name = "Node 12"
                        },
                        new
                        {
                            NodeId = 13,
                            Name = "Node 13"
                        },
                        new
                        {
                            NodeId = 14,
                            Name = "Node 14"
                        },
                        new
                        {
                            NodeId = 15,
                            Name = "Node 15"
                        },
                        new
                        {
                            NodeId = 16,
                            Name = "Node 16"
                        },
                        new
                        {
                            NodeId = 17,
                            Name = "Node 17"
                        },
                        new
                        {
                            NodeId = 18,
                            Name = "Node 18"
                        },
                        new
                        {
                            NodeId = 19,
                            Name = "Node 19"
                        },
                        new
                        {
                            NodeId = 20,
                            Name = "Node 20"
                        });
                });

            modelBuilder.Entity("ParentChildAccess.Model.NodeRelation", b =>
                {
                    b.Property<int>("RelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationId"));

                    b.Property<int>("ChildNodeId")
                        .HasColumnType("int");

                    b.Property<int>("ParentNodeId")
                        .HasColumnType("int");

                    b.HasKey("RelationId");

                    b.HasIndex("ChildNodeId");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("NodeRelations");

                    b.HasData(
                        new
                        {
                            RelationId = 1,
                            ChildNodeId = 2,
                            ParentNodeId = 1
                        },
                        new
                        {
                            RelationId = 2,
                            ChildNodeId = 3,
                            ParentNodeId = 1
                        },
                        new
                        {
                            RelationId = 3,
                            ChildNodeId = 4,
                            ParentNodeId = 2
                        },
                        new
                        {
                            RelationId = 4,
                            ChildNodeId = 5,
                            ParentNodeId = 2
                        },
                        new
                        {
                            RelationId = 5,
                            ChildNodeId = 6,
                            ParentNodeId = 3
                        },
                        new
                        {
                            RelationId = 6,
                            ChildNodeId = 7,
                            ParentNodeId = 3
                        },
                        new
                        {
                            RelationId = 7,
                            ChildNodeId = 8,
                            ParentNodeId = 4
                        },
                        new
                        {
                            RelationId = 8,
                            ChildNodeId = 9,
                            ParentNodeId = 4
                        },
                        new
                        {
                            RelationId = 9,
                            ChildNodeId = 10,
                            ParentNodeId = 5
                        },
                        new
                        {
                            RelationId = 10,
                            ChildNodeId = 11,
                            ParentNodeId = 5
                        },
                        new
                        {
                            RelationId = 11,
                            ChildNodeId = 12,
                            ParentNodeId = 6
                        },
                        new
                        {
                            RelationId = 12,
                            ChildNodeId = 13,
                            ParentNodeId = 6
                        },
                        new
                        {
                            RelationId = 13,
                            ChildNodeId = 14,
                            ParentNodeId = 7
                        },
                        new
                        {
                            RelationId = 14,
                            ChildNodeId = 15,
                            ParentNodeId = 7
                        },
                        new
                        {
                            RelationId = 15,
                            ChildNodeId = 16,
                            ParentNodeId = 8
                        },
                        new
                        {
                            RelationId = 16,
                            ChildNodeId = 17,
                            ParentNodeId = 8
                        },
                        new
                        {
                            RelationId = 17,
                            ChildNodeId = 18,
                            ParentNodeId = 9
                        },
                        new
                        {
                            RelationId = 18,
                            ChildNodeId = 19,
                            ParentNodeId = 9
                        },
                        new
                        {
                            RelationId = 19,
                            ChildNodeId = 20,
                            ParentNodeId = 10
                        });
                });

            modelBuilder.Entity("ParentChildAccess.Model.NodeRelation", b =>
                {
                    b.HasOne("ParentChildAccess.Model.Node", "ChildNode")
                        .WithMany()
                        .HasForeignKey("ChildNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParentChildAccess.Model.Node", "ParentNode")
                        .WithMany()
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildNode");

                    b.Navigation("ParentNode");
                });
#pragma warning restore 612, 618
        }
    }
}
