// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathBasedAccess.Data;

#nullable disable

namespace PathBasedAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240229202712_InitDbWithDefData")]
    partial class InitDbWithDefData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PathBasedAccess.Model.Node", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NodeId");

                    b.HasIndex("Path")
                        .HasDatabaseName("IDX_Node_Path");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            NodeId = 1,
                            Name = "Node 1",
                            Path = "1"
                        },
                        new
                        {
                            NodeId = 2,
                            Name = "Node 2",
                            Path = "1/2"
                        },
                        new
                        {
                            NodeId = 4,
                            Name = "Node 4",
                            Path = "1/2/4"
                        },
                        new
                        {
                            NodeId = 8,
                            Name = "Node 8",
                            Path = "1/2/4/8"
                        },
                        new
                        {
                            NodeId = 16,
                            Name = "Node 16",
                            Path = "1/2/4/8/16"
                        },
                        new
                        {
                            NodeId = 32,
                            Name = "Node 32",
                            Path = "1/2/4/8/16/32"
                        },
                        new
                        {
                            NodeId = 64,
                            Name = "Node 64",
                            Path = "1/2/4/8/16/32/64"
                        },
                        new
                        {
                            NodeId = 128,
                            Name = "Node 128",
                            Path = "1/2/4/8/16/32/64/128"
                        },
                        new
                        {
                            NodeId = 129,
                            Name = "Node 129",
                            Path = "1/2/4/8/16/32/64/129"
                        },
                        new
                        {
                            NodeId = 65,
                            Name = "Node 65",
                            Path = "1/2/4/8/16/32/65"
                        },
                        new
                        {
                            NodeId = 130,
                            Name = "Node 130",
                            Path = "1/2/4/8/16/32/65/130"
                        },
                        new
                        {
                            NodeId = 131,
                            Name = "Node 131",
                            Path = "1/2/4/8/16/32/65/131"
                        },
                        new
                        {
                            NodeId = 33,
                            Name = "Node 33",
                            Path = "1/2/4/8/16/33"
                        },
                        new
                        {
                            NodeId = 66,
                            Name = "Node 66",
                            Path = "1/2/4/8/16/33/66"
                        },
                        new
                        {
                            NodeId = 132,
                            Name = "Node 132",
                            Path = "1/2/4/8/16/33/66/132"
                        },
                        new
                        {
                            NodeId = 133,
                            Name = "Node 133",
                            Path = "1/2/4/8/16/33/66/133"
                        },
                        new
                        {
                            NodeId = 67,
                            Name = "Node 67",
                            Path = "1/2/4/8/16/33/67"
                        },
                        new
                        {
                            NodeId = 134,
                            Name = "Node 134",
                            Path = "1/2/4/8/16/33/67/134"
                        },
                        new
                        {
                            NodeId = 135,
                            Name = "Node 135",
                            Path = "1/2/4/8/16/33/67/135"
                        },
                        new
                        {
                            NodeId = 17,
                            Name = "Node 17",
                            Path = "1/2/4/8/17"
                        },
                        new
                        {
                            NodeId = 34,
                            Name = "Node 34",
                            Path = "1/2/4/8/17/34"
                        },
                        new
                        {
                            NodeId = 68,
                            Name = "Node 68",
                            Path = "1/2/4/8/17/34/68"
                        },
                        new
                        {
                            NodeId = 136,
                            Name = "Node 136",
                            Path = "1/2/4/8/17/34/68/136"
                        },
                        new
                        {
                            NodeId = 137,
                            Name = "Node 137",
                            Path = "1/2/4/8/17/34/68/137"
                        },
                        new
                        {
                            NodeId = 69,
                            Name = "Node 69",
                            Path = "1/2/4/8/17/34/69"
                        },
                        new
                        {
                            NodeId = 138,
                            Name = "Node 138",
                            Path = "1/2/4/8/17/34/69/138"
                        },
                        new
                        {
                            NodeId = 139,
                            Name = "Node 139",
                            Path = "1/2/4/8/17/34/69/139"
                        },
                        new
                        {
                            NodeId = 35,
                            Name = "Node 35",
                            Path = "1/2/4/8/17/35"
                        },
                        new
                        {
                            NodeId = 70,
                            Name = "Node 70",
                            Path = "1/2/4/8/17/35/70"
                        },
                        new
                        {
                            NodeId = 140,
                            Name = "Node 140",
                            Path = "1/2/4/8/17/35/70/140"
                        },
                        new
                        {
                            NodeId = 141,
                            Name = "Node 141",
                            Path = "1/2/4/8/17/35/70/141"
                        },
                        new
                        {
                            NodeId = 71,
                            Name = "Node 71",
                            Path = "1/2/4/8/17/35/71"
                        },
                        new
                        {
                            NodeId = 142,
                            Name = "Node 142",
                            Path = "1/2/4/8/17/35/71/142"
                        },
                        new
                        {
                            NodeId = 143,
                            Name = "Node 143",
                            Path = "1/2/4/8/17/35/71/143"
                        },
                        new
                        {
                            NodeId = 9,
                            Name = "Node 9",
                            Path = "1/2/4/9"
                        },
                        new
                        {
                            NodeId = 18,
                            Name = "Node 18",
                            Path = "1/2/4/9/18"
                        },
                        new
                        {
                            NodeId = 36,
                            Name = "Node 36",
                            Path = "1/2/4/9/18/36"
                        },
                        new
                        {
                            NodeId = 72,
                            Name = "Node 72",
                            Path = "1/2/4/9/18/36/72"
                        },
                        new
                        {
                            NodeId = 144,
                            Name = "Node 144",
                            Path = "1/2/4/9/18/36/72/144"
                        },
                        new
                        {
                            NodeId = 145,
                            Name = "Node 145",
                            Path = "1/2/4/9/18/36/72/145"
                        },
                        new
                        {
                            NodeId = 73,
                            Name = "Node 73",
                            Path = "1/2/4/9/18/36/73"
                        },
                        new
                        {
                            NodeId = 146,
                            Name = "Node 146",
                            Path = "1/2/4/9/18/36/73/146"
                        },
                        new
                        {
                            NodeId = 147,
                            Name = "Node 147",
                            Path = "1/2/4/9/18/36/73/147"
                        },
                        new
                        {
                            NodeId = 37,
                            Name = "Node 37",
                            Path = "1/2/4/9/18/37"
                        },
                        new
                        {
                            NodeId = 74,
                            Name = "Node 74",
                            Path = "1/2/4/9/18/37/74"
                        },
                        new
                        {
                            NodeId = 148,
                            Name = "Node 148",
                            Path = "1/2/4/9/18/37/74/148"
                        },
                        new
                        {
                            NodeId = 149,
                            Name = "Node 149",
                            Path = "1/2/4/9/18/37/74/149"
                        },
                        new
                        {
                            NodeId = 75,
                            Name = "Node 75",
                            Path = "1/2/4/9/18/37/75"
                        },
                        new
                        {
                            NodeId = 150,
                            Name = "Node 150",
                            Path = "1/2/4/9/18/37/75/150"
                        },
                        new
                        {
                            NodeId = 151,
                            Name = "Node 151",
                            Path = "1/2/4/9/18/37/75/151"
                        },
                        new
                        {
                            NodeId = 19,
                            Name = "Node 19",
                            Path = "1/2/4/9/19"
                        },
                        new
                        {
                            NodeId = 38,
                            Name = "Node 38",
                            Path = "1/2/4/9/19/38"
                        },
                        new
                        {
                            NodeId = 76,
                            Name = "Node 76",
                            Path = "1/2/4/9/19/38/76"
                        },
                        new
                        {
                            NodeId = 152,
                            Name = "Node 152",
                            Path = "1/2/4/9/19/38/76/152"
                        },
                        new
                        {
                            NodeId = 153,
                            Name = "Node 153",
                            Path = "1/2/4/9/19/38/76/153"
                        },
                        new
                        {
                            NodeId = 77,
                            Name = "Node 77",
                            Path = "1/2/4/9/19/38/77"
                        },
                        new
                        {
                            NodeId = 154,
                            Name = "Node 154",
                            Path = "1/2/4/9/19/38/77/154"
                        },
                        new
                        {
                            NodeId = 155,
                            Name = "Node 155",
                            Path = "1/2/4/9/19/38/77/155"
                        },
                        new
                        {
                            NodeId = 39,
                            Name = "Node 39",
                            Path = "1/2/4/9/19/39"
                        },
                        new
                        {
                            NodeId = 78,
                            Name = "Node 78",
                            Path = "1/2/4/9/19/39/78"
                        },
                        new
                        {
                            NodeId = 156,
                            Name = "Node 156",
                            Path = "1/2/4/9/19/39/78/156"
                        },
                        new
                        {
                            NodeId = 157,
                            Name = "Node 157",
                            Path = "1/2/4/9/19/39/78/157"
                        },
                        new
                        {
                            NodeId = 79,
                            Name = "Node 79",
                            Path = "1/2/4/9/19/39/79"
                        },
                        new
                        {
                            NodeId = 158,
                            Name = "Node 158",
                            Path = "1/2/4/9/19/39/79/158"
                        },
                        new
                        {
                            NodeId = 159,
                            Name = "Node 159",
                            Path = "1/2/4/9/19/39/79/159"
                        },
                        new
                        {
                            NodeId = 5,
                            Name = "Node 5",
                            Path = "1/2/5"
                        },
                        new
                        {
                            NodeId = 10,
                            Name = "Node 10",
                            Path = "1/2/5/10"
                        },
                        new
                        {
                            NodeId = 20,
                            Name = "Node 20",
                            Path = "1/2/5/10/20"
                        },
                        new
                        {
                            NodeId = 40,
                            Name = "Node 40",
                            Path = "1/2/5/10/20/40"
                        },
                        new
                        {
                            NodeId = 80,
                            Name = "Node 80",
                            Path = "1/2/5/10/20/40/80"
                        },
                        new
                        {
                            NodeId = 160,
                            Name = "Node 160",
                            Path = "1/2/5/10/20/40/80/160"
                        },
                        new
                        {
                            NodeId = 161,
                            Name = "Node 161",
                            Path = "1/2/5/10/20/40/80/161"
                        },
                        new
                        {
                            NodeId = 81,
                            Name = "Node 81",
                            Path = "1/2/5/10/20/40/81"
                        },
                        new
                        {
                            NodeId = 162,
                            Name = "Node 162",
                            Path = "1/2/5/10/20/40/81/162"
                        },
                        new
                        {
                            NodeId = 163,
                            Name = "Node 163",
                            Path = "1/2/5/10/20/40/81/163"
                        },
                        new
                        {
                            NodeId = 41,
                            Name = "Node 41",
                            Path = "1/2/5/10/20/41"
                        },
                        new
                        {
                            NodeId = 82,
                            Name = "Node 82",
                            Path = "1/2/5/10/20/41/82"
                        },
                        new
                        {
                            NodeId = 164,
                            Name = "Node 164",
                            Path = "1/2/5/10/20/41/82/164"
                        },
                        new
                        {
                            NodeId = 165,
                            Name = "Node 165",
                            Path = "1/2/5/10/20/41/82/165"
                        },
                        new
                        {
                            NodeId = 83,
                            Name = "Node 83",
                            Path = "1/2/5/10/20/41/83"
                        },
                        new
                        {
                            NodeId = 166,
                            Name = "Node 166",
                            Path = "1/2/5/10/20/41/83/166"
                        },
                        new
                        {
                            NodeId = 167,
                            Name = "Node 167",
                            Path = "1/2/5/10/20/41/83/167"
                        },
                        new
                        {
                            NodeId = 21,
                            Name = "Node 21",
                            Path = "1/2/5/10/21"
                        },
                        new
                        {
                            NodeId = 42,
                            Name = "Node 42",
                            Path = "1/2/5/10/21/42"
                        },
                        new
                        {
                            NodeId = 84,
                            Name = "Node 84",
                            Path = "1/2/5/10/21/42/84"
                        },
                        new
                        {
                            NodeId = 168,
                            Name = "Node 168",
                            Path = "1/2/5/10/21/42/84/168"
                        },
                        new
                        {
                            NodeId = 169,
                            Name = "Node 169",
                            Path = "1/2/5/10/21/42/84/169"
                        },
                        new
                        {
                            NodeId = 85,
                            Name = "Node 85",
                            Path = "1/2/5/10/21/42/85"
                        },
                        new
                        {
                            NodeId = 170,
                            Name = "Node 170",
                            Path = "1/2/5/10/21/42/85/170"
                        },
                        new
                        {
                            NodeId = 171,
                            Name = "Node 171",
                            Path = "1/2/5/10/21/42/85/171"
                        },
                        new
                        {
                            NodeId = 43,
                            Name = "Node 43",
                            Path = "1/2/5/10/21/43"
                        },
                        new
                        {
                            NodeId = 86,
                            Name = "Node 86",
                            Path = "1/2/5/10/21/43/86"
                        },
                        new
                        {
                            NodeId = 172,
                            Name = "Node 172",
                            Path = "1/2/5/10/21/43/86/172"
                        },
                        new
                        {
                            NodeId = 173,
                            Name = "Node 173",
                            Path = "1/2/5/10/21/43/86/173"
                        },
                        new
                        {
                            NodeId = 87,
                            Name = "Node 87",
                            Path = "1/2/5/10/21/43/87"
                        },
                        new
                        {
                            NodeId = 174,
                            Name = "Node 174",
                            Path = "1/2/5/10/21/43/87/174"
                        },
                        new
                        {
                            NodeId = 175,
                            Name = "Node 175",
                            Path = "1/2/5/10/21/43/87/175"
                        },
                        new
                        {
                            NodeId = 11,
                            Name = "Node 11",
                            Path = "1/2/5/11"
                        },
                        new
                        {
                            NodeId = 22,
                            Name = "Node 22",
                            Path = "1/2/5/11/22"
                        },
                        new
                        {
                            NodeId = 44,
                            Name = "Node 44",
                            Path = "1/2/5/11/22/44"
                        },
                        new
                        {
                            NodeId = 88,
                            Name = "Node 88",
                            Path = "1/2/5/11/22/44/88"
                        },
                        new
                        {
                            NodeId = 176,
                            Name = "Node 176",
                            Path = "1/2/5/11/22/44/88/176"
                        },
                        new
                        {
                            NodeId = 177,
                            Name = "Node 177",
                            Path = "1/2/5/11/22/44/88/177"
                        },
                        new
                        {
                            NodeId = 89,
                            Name = "Node 89",
                            Path = "1/2/5/11/22/44/89"
                        },
                        new
                        {
                            NodeId = 178,
                            Name = "Node 178",
                            Path = "1/2/5/11/22/44/89/178"
                        },
                        new
                        {
                            NodeId = 179,
                            Name = "Node 179",
                            Path = "1/2/5/11/22/44/89/179"
                        },
                        new
                        {
                            NodeId = 45,
                            Name = "Node 45",
                            Path = "1/2/5/11/22/45"
                        },
                        new
                        {
                            NodeId = 90,
                            Name = "Node 90",
                            Path = "1/2/5/11/22/45/90"
                        },
                        new
                        {
                            NodeId = 180,
                            Name = "Node 180",
                            Path = "1/2/5/11/22/45/90/180"
                        },
                        new
                        {
                            NodeId = 181,
                            Name = "Node 181",
                            Path = "1/2/5/11/22/45/90/181"
                        },
                        new
                        {
                            NodeId = 91,
                            Name = "Node 91",
                            Path = "1/2/5/11/22/45/91"
                        },
                        new
                        {
                            NodeId = 182,
                            Name = "Node 182",
                            Path = "1/2/5/11/22/45/91/182"
                        },
                        new
                        {
                            NodeId = 183,
                            Name = "Node 183",
                            Path = "1/2/5/11/22/45/91/183"
                        },
                        new
                        {
                            NodeId = 23,
                            Name = "Node 23",
                            Path = "1/2/5/11/23"
                        },
                        new
                        {
                            NodeId = 46,
                            Name = "Node 46",
                            Path = "1/2/5/11/23/46"
                        },
                        new
                        {
                            NodeId = 92,
                            Name = "Node 92",
                            Path = "1/2/5/11/23/46/92"
                        },
                        new
                        {
                            NodeId = 184,
                            Name = "Node 184",
                            Path = "1/2/5/11/23/46/92/184"
                        },
                        new
                        {
                            NodeId = 185,
                            Name = "Node 185",
                            Path = "1/2/5/11/23/46/92/185"
                        },
                        new
                        {
                            NodeId = 93,
                            Name = "Node 93",
                            Path = "1/2/5/11/23/46/93"
                        },
                        new
                        {
                            NodeId = 186,
                            Name = "Node 186",
                            Path = "1/2/5/11/23/46/93/186"
                        },
                        new
                        {
                            NodeId = 187,
                            Name = "Node 187",
                            Path = "1/2/5/11/23/46/93/187"
                        },
                        new
                        {
                            NodeId = 47,
                            Name = "Node 47",
                            Path = "1/2/5/11/23/47"
                        },
                        new
                        {
                            NodeId = 94,
                            Name = "Node 94",
                            Path = "1/2/5/11/23/47/94"
                        },
                        new
                        {
                            NodeId = 188,
                            Name = "Node 188",
                            Path = "1/2/5/11/23/47/94/188"
                        },
                        new
                        {
                            NodeId = 189,
                            Name = "Node 189",
                            Path = "1/2/5/11/23/47/94/189"
                        },
                        new
                        {
                            NodeId = 95,
                            Name = "Node 95",
                            Path = "1/2/5/11/23/47/95"
                        },
                        new
                        {
                            NodeId = 190,
                            Name = "Node 190",
                            Path = "1/2/5/11/23/47/95/190"
                        },
                        new
                        {
                            NodeId = 191,
                            Name = "Node 191",
                            Path = "1/2/5/11/23/47/95/191"
                        },
                        new
                        {
                            NodeId = 3,
                            Name = "Node 3",
                            Path = "1/3"
                        },
                        new
                        {
                            NodeId = 6,
                            Name = "Node 6",
                            Path = "1/3/6"
                        },
                        new
                        {
                            NodeId = 12,
                            Name = "Node 12",
                            Path = "1/3/6/12"
                        },
                        new
                        {
                            NodeId = 24,
                            Name = "Node 24",
                            Path = "1/3/6/12/24"
                        },
                        new
                        {
                            NodeId = 48,
                            Name = "Node 48",
                            Path = "1/3/6/12/24/48"
                        },
                        new
                        {
                            NodeId = 96,
                            Name = "Node 96",
                            Path = "1/3/6/12/24/48/96"
                        },
                        new
                        {
                            NodeId = 192,
                            Name = "Node 192",
                            Path = "1/3/6/12/24/48/96/192"
                        },
                        new
                        {
                            NodeId = 193,
                            Name = "Node 193",
                            Path = "1/3/6/12/24/48/96/193"
                        },
                        new
                        {
                            NodeId = 97,
                            Name = "Node 97",
                            Path = "1/3/6/12/24/48/97"
                        },
                        new
                        {
                            NodeId = 194,
                            Name = "Node 194",
                            Path = "1/3/6/12/24/48/97/194"
                        },
                        new
                        {
                            NodeId = 195,
                            Name = "Node 195",
                            Path = "1/3/6/12/24/48/97/195"
                        },
                        new
                        {
                            NodeId = 49,
                            Name = "Node 49",
                            Path = "1/3/6/12/24/49"
                        },
                        new
                        {
                            NodeId = 98,
                            Name = "Node 98",
                            Path = "1/3/6/12/24/49/98"
                        },
                        new
                        {
                            NodeId = 196,
                            Name = "Node 196",
                            Path = "1/3/6/12/24/49/98/196"
                        },
                        new
                        {
                            NodeId = 197,
                            Name = "Node 197",
                            Path = "1/3/6/12/24/49/98/197"
                        },
                        new
                        {
                            NodeId = 99,
                            Name = "Node 99",
                            Path = "1/3/6/12/24/49/99"
                        },
                        new
                        {
                            NodeId = 198,
                            Name = "Node 198",
                            Path = "1/3/6/12/24/49/99/198"
                        },
                        new
                        {
                            NodeId = 199,
                            Name = "Node 199",
                            Path = "1/3/6/12/24/49/99/199"
                        },
                        new
                        {
                            NodeId = 25,
                            Name = "Node 25",
                            Path = "1/3/6/12/25"
                        },
                        new
                        {
                            NodeId = 50,
                            Name = "Node 50",
                            Path = "1/3/6/12/25/50"
                        },
                        new
                        {
                            NodeId = 100,
                            Name = "Node 100",
                            Path = "1/3/6/12/25/50/100"
                        },
                        new
                        {
                            NodeId = 200,
                            Name = "Node 200",
                            Path = "1/3/6/12/25/50/100/200"
                        },
                        new
                        {
                            NodeId = 101,
                            Name = "Node 101",
                            Path = "1/3/6/12/25/50/101"
                        },
                        new
                        {
                            NodeId = 51,
                            Name = "Node 51",
                            Path = "1/3/6/12/25/51"
                        },
                        new
                        {
                            NodeId = 102,
                            Name = "Node 102",
                            Path = "1/3/6/12/25/51/102"
                        },
                        new
                        {
                            NodeId = 103,
                            Name = "Node 103",
                            Path = "1/3/6/12/25/51/103"
                        },
                        new
                        {
                            NodeId = 13,
                            Name = "Node 13",
                            Path = "1/3/6/13"
                        },
                        new
                        {
                            NodeId = 26,
                            Name = "Node 26",
                            Path = "1/3/6/13/26"
                        },
                        new
                        {
                            NodeId = 52,
                            Name = "Node 52",
                            Path = "1/3/6/13/26/52"
                        },
                        new
                        {
                            NodeId = 104,
                            Name = "Node 104",
                            Path = "1/3/6/13/26/52/104"
                        },
                        new
                        {
                            NodeId = 105,
                            Name = "Node 105",
                            Path = "1/3/6/13/26/52/105"
                        },
                        new
                        {
                            NodeId = 53,
                            Name = "Node 53",
                            Path = "1/3/6/13/26/53"
                        },
                        new
                        {
                            NodeId = 106,
                            Name = "Node 106",
                            Path = "1/3/6/13/26/53/106"
                        },
                        new
                        {
                            NodeId = 107,
                            Name = "Node 107",
                            Path = "1/3/6/13/26/53/107"
                        },
                        new
                        {
                            NodeId = 27,
                            Name = "Node 27",
                            Path = "1/3/6/13/27"
                        },
                        new
                        {
                            NodeId = 54,
                            Name = "Node 54",
                            Path = "1/3/6/13/27/54"
                        },
                        new
                        {
                            NodeId = 108,
                            Name = "Node 108",
                            Path = "1/3/6/13/27/54/108"
                        },
                        new
                        {
                            NodeId = 109,
                            Name = "Node 109",
                            Path = "1/3/6/13/27/54/109"
                        },
                        new
                        {
                            NodeId = 55,
                            Name = "Node 55",
                            Path = "1/3/6/13/27/55"
                        },
                        new
                        {
                            NodeId = 110,
                            Name = "Node 110",
                            Path = "1/3/6/13/27/55/110"
                        },
                        new
                        {
                            NodeId = 111,
                            Name = "Node 111",
                            Path = "1/3/6/13/27/55/111"
                        },
                        new
                        {
                            NodeId = 7,
                            Name = "Node 7",
                            Path = "1/3/7"
                        },
                        new
                        {
                            NodeId = 14,
                            Name = "Node 14",
                            Path = "1/3/7/14"
                        },
                        new
                        {
                            NodeId = 28,
                            Name = "Node 28",
                            Path = "1/3/7/14/28"
                        },
                        new
                        {
                            NodeId = 56,
                            Name = "Node 56",
                            Path = "1/3/7/14/28/56"
                        },
                        new
                        {
                            NodeId = 112,
                            Name = "Node 112",
                            Path = "1/3/7/14/28/56/112"
                        },
                        new
                        {
                            NodeId = 113,
                            Name = "Node 113",
                            Path = "1/3/7/14/28/56/113"
                        },
                        new
                        {
                            NodeId = 57,
                            Name = "Node 57",
                            Path = "1/3/7/14/28/57"
                        },
                        new
                        {
                            NodeId = 114,
                            Name = "Node 114",
                            Path = "1/3/7/14/28/57/114"
                        },
                        new
                        {
                            NodeId = 115,
                            Name = "Node 115",
                            Path = "1/3/7/14/28/57/115"
                        },
                        new
                        {
                            NodeId = 29,
                            Name = "Node 29",
                            Path = "1/3/7/14/29"
                        },
                        new
                        {
                            NodeId = 58,
                            Name = "Node 58",
                            Path = "1/3/7/14/29/58"
                        },
                        new
                        {
                            NodeId = 116,
                            Name = "Node 116",
                            Path = "1/3/7/14/29/58/116"
                        },
                        new
                        {
                            NodeId = 117,
                            Name = "Node 117",
                            Path = "1/3/7/14/29/58/117"
                        },
                        new
                        {
                            NodeId = 59,
                            Name = "Node 59",
                            Path = "1/3/7/14/29/59"
                        },
                        new
                        {
                            NodeId = 118,
                            Name = "Node 118",
                            Path = "1/3/7/14/29/59/118"
                        },
                        new
                        {
                            NodeId = 119,
                            Name = "Node 119",
                            Path = "1/3/7/14/29/59/119"
                        },
                        new
                        {
                            NodeId = 15,
                            Name = "Node 15",
                            Path = "1/3/7/15"
                        },
                        new
                        {
                            NodeId = 30,
                            Name = "Node 30",
                            Path = "1/3/7/15/30"
                        },
                        new
                        {
                            NodeId = 60,
                            Name = "Node 60",
                            Path = "1/3/7/15/30/60"
                        },
                        new
                        {
                            NodeId = 120,
                            Name = "Node 120",
                            Path = "1/3/7/15/30/60/120"
                        },
                        new
                        {
                            NodeId = 121,
                            Name = "Node 121",
                            Path = "1/3/7/15/30/60/121"
                        },
                        new
                        {
                            NodeId = 61,
                            Name = "Node 61",
                            Path = "1/3/7/15/30/61"
                        },
                        new
                        {
                            NodeId = 122,
                            Name = "Node 122",
                            Path = "1/3/7/15/30/61/122"
                        },
                        new
                        {
                            NodeId = 123,
                            Name = "Node 123",
                            Path = "1/3/7/15/30/61/123"
                        },
                        new
                        {
                            NodeId = 31,
                            Name = "Node 31",
                            Path = "1/3/7/15/31"
                        },
                        new
                        {
                            NodeId = 62,
                            Name = "Node 62",
                            Path = "1/3/7/15/31/62"
                        },
                        new
                        {
                            NodeId = 124,
                            Name = "Node 124",
                            Path = "1/3/7/15/31/62/124"
                        },
                        new
                        {
                            NodeId = 125,
                            Name = "Node 125",
                            Path = "1/3/7/15/31/62/125"
                        },
                        new
                        {
                            NodeId = 63,
                            Name = "Node 63",
                            Path = "1/3/7/15/31/63"
                        },
                        new
                        {
                            NodeId = 126,
                            Name = "Node 126",
                            Path = "1/3/7/15/31/63/126"
                        },
                        new
                        {
                            NodeId = 127,
                            Name = "Node 127",
                            Path = "1/3/7/15/31/63/127"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
