// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NestedSetsAccess.Data;

#nullable disable

namespace NestedSetsAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240229203049_InitDbWithDefData")]
    partial class InitDbWithDefData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NestedSetsAccess.Model.Node", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeId"));

                    b.Property<int>("Left")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<int>("Right")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.HasKey("NodeId");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            NodeId = 128,
                            Left = 8,
                            Name = "Node 128",
                            Right = 9
                        },
                        new
                        {
                            NodeId = 129,
                            Left = 10,
                            Name = "Node 129",
                            Right = 11
                        },
                        new
                        {
                            NodeId = 64,
                            Left = 7,
                            Name = "Node 64",
                            Right = 12
                        },
                        new
                        {
                            NodeId = 130,
                            Left = 14,
                            Name = "Node 130",
                            Right = 15
                        },
                        new
                        {
                            NodeId = 131,
                            Left = 16,
                            Name = "Node 131",
                            Right = 17
                        },
                        new
                        {
                            NodeId = 65,
                            Left = 13,
                            Name = "Node 65",
                            Right = 18
                        },
                        new
                        {
                            NodeId = 32,
                            Left = 6,
                            Name = "Node 32",
                            Right = 19
                        },
                        new
                        {
                            NodeId = 132,
                            Left = 22,
                            Name = "Node 132",
                            Right = 23
                        },
                        new
                        {
                            NodeId = 133,
                            Left = 24,
                            Name = "Node 133",
                            Right = 25
                        },
                        new
                        {
                            NodeId = 66,
                            Left = 21,
                            Name = "Node 66",
                            Right = 26
                        },
                        new
                        {
                            NodeId = 134,
                            Left = 28,
                            Name = "Node 134",
                            Right = 29
                        },
                        new
                        {
                            NodeId = 135,
                            Left = 30,
                            Name = "Node 135",
                            Right = 31
                        },
                        new
                        {
                            NodeId = 67,
                            Left = 27,
                            Name = "Node 67",
                            Right = 32
                        },
                        new
                        {
                            NodeId = 33,
                            Left = 20,
                            Name = "Node 33",
                            Right = 33
                        },
                        new
                        {
                            NodeId = 16,
                            Left = 5,
                            Name = "Node 16",
                            Right = 34
                        },
                        new
                        {
                            NodeId = 136,
                            Left = 38,
                            Name = "Node 136",
                            Right = 39
                        },
                        new
                        {
                            NodeId = 137,
                            Left = 40,
                            Name = "Node 137",
                            Right = 41
                        },
                        new
                        {
                            NodeId = 68,
                            Left = 37,
                            Name = "Node 68",
                            Right = 42
                        },
                        new
                        {
                            NodeId = 138,
                            Left = 44,
                            Name = "Node 138",
                            Right = 45
                        },
                        new
                        {
                            NodeId = 139,
                            Left = 46,
                            Name = "Node 139",
                            Right = 47
                        },
                        new
                        {
                            NodeId = 69,
                            Left = 43,
                            Name = "Node 69",
                            Right = 48
                        },
                        new
                        {
                            NodeId = 34,
                            Left = 36,
                            Name = "Node 34",
                            Right = 49
                        },
                        new
                        {
                            NodeId = 140,
                            Left = 52,
                            Name = "Node 140",
                            Right = 53
                        },
                        new
                        {
                            NodeId = 141,
                            Left = 54,
                            Name = "Node 141",
                            Right = 55
                        },
                        new
                        {
                            NodeId = 70,
                            Left = 51,
                            Name = "Node 70",
                            Right = 56
                        },
                        new
                        {
                            NodeId = 142,
                            Left = 58,
                            Name = "Node 142",
                            Right = 59
                        },
                        new
                        {
                            NodeId = 143,
                            Left = 60,
                            Name = "Node 143",
                            Right = 61
                        },
                        new
                        {
                            NodeId = 71,
                            Left = 57,
                            Name = "Node 71",
                            Right = 62
                        },
                        new
                        {
                            NodeId = 35,
                            Left = 50,
                            Name = "Node 35",
                            Right = 63
                        },
                        new
                        {
                            NodeId = 17,
                            Left = 35,
                            Name = "Node 17",
                            Right = 64
                        },
                        new
                        {
                            NodeId = 8,
                            Left = 4,
                            Name = "Node 8",
                            Right = 65
                        },
                        new
                        {
                            NodeId = 144,
                            Left = 70,
                            Name = "Node 144",
                            Right = 71
                        },
                        new
                        {
                            NodeId = 145,
                            Left = 72,
                            Name = "Node 145",
                            Right = 73
                        },
                        new
                        {
                            NodeId = 72,
                            Left = 69,
                            Name = "Node 72",
                            Right = 74
                        },
                        new
                        {
                            NodeId = 146,
                            Left = 76,
                            Name = "Node 146",
                            Right = 77
                        },
                        new
                        {
                            NodeId = 147,
                            Left = 78,
                            Name = "Node 147",
                            Right = 79
                        },
                        new
                        {
                            NodeId = 73,
                            Left = 75,
                            Name = "Node 73",
                            Right = 80
                        },
                        new
                        {
                            NodeId = 36,
                            Left = 68,
                            Name = "Node 36",
                            Right = 81
                        },
                        new
                        {
                            NodeId = 148,
                            Left = 84,
                            Name = "Node 148",
                            Right = 85
                        },
                        new
                        {
                            NodeId = 149,
                            Left = 86,
                            Name = "Node 149",
                            Right = 87
                        },
                        new
                        {
                            NodeId = 74,
                            Left = 83,
                            Name = "Node 74",
                            Right = 88
                        },
                        new
                        {
                            NodeId = 150,
                            Left = 90,
                            Name = "Node 150",
                            Right = 91
                        },
                        new
                        {
                            NodeId = 151,
                            Left = 92,
                            Name = "Node 151",
                            Right = 93
                        },
                        new
                        {
                            NodeId = 75,
                            Left = 89,
                            Name = "Node 75",
                            Right = 94
                        },
                        new
                        {
                            NodeId = 37,
                            Left = 82,
                            Name = "Node 37",
                            Right = 95
                        },
                        new
                        {
                            NodeId = 18,
                            Left = 67,
                            Name = "Node 18",
                            Right = 96
                        },
                        new
                        {
                            NodeId = 152,
                            Left = 100,
                            Name = "Node 152",
                            Right = 101
                        },
                        new
                        {
                            NodeId = 153,
                            Left = 102,
                            Name = "Node 153",
                            Right = 103
                        },
                        new
                        {
                            NodeId = 76,
                            Left = 99,
                            Name = "Node 76",
                            Right = 104
                        },
                        new
                        {
                            NodeId = 154,
                            Left = 106,
                            Name = "Node 154",
                            Right = 107
                        },
                        new
                        {
                            NodeId = 155,
                            Left = 108,
                            Name = "Node 155",
                            Right = 109
                        },
                        new
                        {
                            NodeId = 77,
                            Left = 105,
                            Name = "Node 77",
                            Right = 110
                        },
                        new
                        {
                            NodeId = 38,
                            Left = 98,
                            Name = "Node 38",
                            Right = 111
                        },
                        new
                        {
                            NodeId = 156,
                            Left = 114,
                            Name = "Node 156",
                            Right = 115
                        },
                        new
                        {
                            NodeId = 157,
                            Left = 116,
                            Name = "Node 157",
                            Right = 117
                        },
                        new
                        {
                            NodeId = 78,
                            Left = 113,
                            Name = "Node 78",
                            Right = 118
                        },
                        new
                        {
                            NodeId = 158,
                            Left = 120,
                            Name = "Node 158",
                            Right = 121
                        },
                        new
                        {
                            NodeId = 159,
                            Left = 122,
                            Name = "Node 159",
                            Right = 123
                        },
                        new
                        {
                            NodeId = 79,
                            Left = 119,
                            Name = "Node 79",
                            Right = 124
                        },
                        new
                        {
                            NodeId = 39,
                            Left = 112,
                            Name = "Node 39",
                            Right = 125
                        },
                        new
                        {
                            NodeId = 19,
                            Left = 97,
                            Name = "Node 19",
                            Right = 126
                        },
                        new
                        {
                            NodeId = 9,
                            Left = 66,
                            Name = "Node 9",
                            Right = 127
                        },
                        new
                        {
                            NodeId = 4,
                            Left = 3,
                            Name = "Node 4",
                            Right = 128
                        },
                        new
                        {
                            NodeId = 160,
                            Left = 134,
                            Name = "Node 160",
                            Right = 135
                        },
                        new
                        {
                            NodeId = 161,
                            Left = 136,
                            Name = "Node 161",
                            Right = 137
                        },
                        new
                        {
                            NodeId = 80,
                            Left = 133,
                            Name = "Node 80",
                            Right = 138
                        },
                        new
                        {
                            NodeId = 162,
                            Left = 140,
                            Name = "Node 162",
                            Right = 141
                        },
                        new
                        {
                            NodeId = 163,
                            Left = 142,
                            Name = "Node 163",
                            Right = 143
                        },
                        new
                        {
                            NodeId = 81,
                            Left = 139,
                            Name = "Node 81",
                            Right = 144
                        },
                        new
                        {
                            NodeId = 40,
                            Left = 132,
                            Name = "Node 40",
                            Right = 145
                        },
                        new
                        {
                            NodeId = 164,
                            Left = 148,
                            Name = "Node 164",
                            Right = 149
                        },
                        new
                        {
                            NodeId = 165,
                            Left = 150,
                            Name = "Node 165",
                            Right = 151
                        },
                        new
                        {
                            NodeId = 82,
                            Left = 147,
                            Name = "Node 82",
                            Right = 152
                        },
                        new
                        {
                            NodeId = 166,
                            Left = 154,
                            Name = "Node 166",
                            Right = 155
                        },
                        new
                        {
                            NodeId = 167,
                            Left = 156,
                            Name = "Node 167",
                            Right = 157
                        },
                        new
                        {
                            NodeId = 83,
                            Left = 153,
                            Name = "Node 83",
                            Right = 158
                        },
                        new
                        {
                            NodeId = 41,
                            Left = 146,
                            Name = "Node 41",
                            Right = 159
                        },
                        new
                        {
                            NodeId = 20,
                            Left = 131,
                            Name = "Node 20",
                            Right = 160
                        },
                        new
                        {
                            NodeId = 168,
                            Left = 164,
                            Name = "Node 168",
                            Right = 165
                        },
                        new
                        {
                            NodeId = 169,
                            Left = 166,
                            Name = "Node 169",
                            Right = 167
                        },
                        new
                        {
                            NodeId = 84,
                            Left = 163,
                            Name = "Node 84",
                            Right = 168
                        },
                        new
                        {
                            NodeId = 170,
                            Left = 170,
                            Name = "Node 170",
                            Right = 171
                        },
                        new
                        {
                            NodeId = 171,
                            Left = 172,
                            Name = "Node 171",
                            Right = 173
                        },
                        new
                        {
                            NodeId = 85,
                            Left = 169,
                            Name = "Node 85",
                            Right = 174
                        },
                        new
                        {
                            NodeId = 42,
                            Left = 162,
                            Name = "Node 42",
                            Right = 175
                        },
                        new
                        {
                            NodeId = 172,
                            Left = 178,
                            Name = "Node 172",
                            Right = 179
                        },
                        new
                        {
                            NodeId = 173,
                            Left = 180,
                            Name = "Node 173",
                            Right = 181
                        },
                        new
                        {
                            NodeId = 86,
                            Left = 177,
                            Name = "Node 86",
                            Right = 182
                        },
                        new
                        {
                            NodeId = 174,
                            Left = 184,
                            Name = "Node 174",
                            Right = 185
                        },
                        new
                        {
                            NodeId = 175,
                            Left = 186,
                            Name = "Node 175",
                            Right = 187
                        },
                        new
                        {
                            NodeId = 87,
                            Left = 183,
                            Name = "Node 87",
                            Right = 188
                        },
                        new
                        {
                            NodeId = 43,
                            Left = 176,
                            Name = "Node 43",
                            Right = 189
                        },
                        new
                        {
                            NodeId = 21,
                            Left = 161,
                            Name = "Node 21",
                            Right = 190
                        },
                        new
                        {
                            NodeId = 10,
                            Left = 130,
                            Name = "Node 10",
                            Right = 191
                        },
                        new
                        {
                            NodeId = 176,
                            Left = 196,
                            Name = "Node 176",
                            Right = 197
                        },
                        new
                        {
                            NodeId = 177,
                            Left = 198,
                            Name = "Node 177",
                            Right = 199
                        },
                        new
                        {
                            NodeId = 88,
                            Left = 195,
                            Name = "Node 88",
                            Right = 200
                        },
                        new
                        {
                            NodeId = 178,
                            Left = 202,
                            Name = "Node 178",
                            Right = 203
                        },
                        new
                        {
                            NodeId = 179,
                            Left = 204,
                            Name = "Node 179",
                            Right = 205
                        },
                        new
                        {
                            NodeId = 89,
                            Left = 201,
                            Name = "Node 89",
                            Right = 206
                        },
                        new
                        {
                            NodeId = 44,
                            Left = 194,
                            Name = "Node 44",
                            Right = 207
                        },
                        new
                        {
                            NodeId = 180,
                            Left = 210,
                            Name = "Node 180",
                            Right = 211
                        },
                        new
                        {
                            NodeId = 181,
                            Left = 212,
                            Name = "Node 181",
                            Right = 213
                        },
                        new
                        {
                            NodeId = 90,
                            Left = 209,
                            Name = "Node 90",
                            Right = 214
                        },
                        new
                        {
                            NodeId = 182,
                            Left = 216,
                            Name = "Node 182",
                            Right = 217
                        },
                        new
                        {
                            NodeId = 183,
                            Left = 218,
                            Name = "Node 183",
                            Right = 219
                        },
                        new
                        {
                            NodeId = 91,
                            Left = 215,
                            Name = "Node 91",
                            Right = 220
                        },
                        new
                        {
                            NodeId = 45,
                            Left = 208,
                            Name = "Node 45",
                            Right = 221
                        },
                        new
                        {
                            NodeId = 22,
                            Left = 193,
                            Name = "Node 22",
                            Right = 222
                        },
                        new
                        {
                            NodeId = 184,
                            Left = 226,
                            Name = "Node 184",
                            Right = 227
                        },
                        new
                        {
                            NodeId = 185,
                            Left = 228,
                            Name = "Node 185",
                            Right = 229
                        },
                        new
                        {
                            NodeId = 92,
                            Left = 225,
                            Name = "Node 92",
                            Right = 230
                        },
                        new
                        {
                            NodeId = 186,
                            Left = 232,
                            Name = "Node 186",
                            Right = 233
                        },
                        new
                        {
                            NodeId = 187,
                            Left = 234,
                            Name = "Node 187",
                            Right = 235
                        },
                        new
                        {
                            NodeId = 93,
                            Left = 231,
                            Name = "Node 93",
                            Right = 236
                        },
                        new
                        {
                            NodeId = 46,
                            Left = 224,
                            Name = "Node 46",
                            Right = 237
                        },
                        new
                        {
                            NodeId = 188,
                            Left = 240,
                            Name = "Node 188",
                            Right = 241
                        },
                        new
                        {
                            NodeId = 189,
                            Left = 242,
                            Name = "Node 189",
                            Right = 243
                        },
                        new
                        {
                            NodeId = 94,
                            Left = 239,
                            Name = "Node 94",
                            Right = 244
                        },
                        new
                        {
                            NodeId = 190,
                            Left = 246,
                            Name = "Node 190",
                            Right = 247
                        },
                        new
                        {
                            NodeId = 191,
                            Left = 248,
                            Name = "Node 191",
                            Right = 249
                        },
                        new
                        {
                            NodeId = 95,
                            Left = 245,
                            Name = "Node 95",
                            Right = 250
                        },
                        new
                        {
                            NodeId = 47,
                            Left = 238,
                            Name = "Node 47",
                            Right = 251
                        },
                        new
                        {
                            NodeId = 23,
                            Left = 223,
                            Name = "Node 23",
                            Right = 252
                        },
                        new
                        {
                            NodeId = 11,
                            Left = 192,
                            Name = "Node 11",
                            Right = 253
                        },
                        new
                        {
                            NodeId = 5,
                            Left = 129,
                            Name = "Node 5",
                            Right = 254
                        },
                        new
                        {
                            NodeId = 2,
                            Left = 2,
                            Name = "Node 2",
                            Right = 255
                        },
                        new
                        {
                            NodeId = 192,
                            Left = 262,
                            Name = "Node 192",
                            Right = 263
                        },
                        new
                        {
                            NodeId = 193,
                            Left = 264,
                            Name = "Node 193",
                            Right = 265
                        },
                        new
                        {
                            NodeId = 96,
                            Left = 261,
                            Name = "Node 96",
                            Right = 266
                        },
                        new
                        {
                            NodeId = 194,
                            Left = 268,
                            Name = "Node 194",
                            Right = 269
                        },
                        new
                        {
                            NodeId = 195,
                            Left = 270,
                            Name = "Node 195",
                            Right = 271
                        },
                        new
                        {
                            NodeId = 97,
                            Left = 267,
                            Name = "Node 97",
                            Right = 272
                        },
                        new
                        {
                            NodeId = 48,
                            Left = 260,
                            Name = "Node 48",
                            Right = 273
                        },
                        new
                        {
                            NodeId = 196,
                            Left = 276,
                            Name = "Node 196",
                            Right = 277
                        },
                        new
                        {
                            NodeId = 197,
                            Left = 278,
                            Name = "Node 197",
                            Right = 279
                        },
                        new
                        {
                            NodeId = 98,
                            Left = 275,
                            Name = "Node 98",
                            Right = 280
                        },
                        new
                        {
                            NodeId = 198,
                            Left = 282,
                            Name = "Node 198",
                            Right = 283
                        },
                        new
                        {
                            NodeId = 199,
                            Left = 284,
                            Name = "Node 199",
                            Right = 285
                        },
                        new
                        {
                            NodeId = 99,
                            Left = 281,
                            Name = "Node 99",
                            Right = 286
                        },
                        new
                        {
                            NodeId = 49,
                            Left = 274,
                            Name = "Node 49",
                            Right = 287
                        },
                        new
                        {
                            NodeId = 24,
                            Left = 259,
                            Name = "Node 24",
                            Right = 288
                        },
                        new
                        {
                            NodeId = 200,
                            Left = 292,
                            Name = "Node 200",
                            Right = 293
                        },
                        new
                        {
                            NodeId = 100,
                            Left = 291,
                            Name = "Node 100",
                            Right = 294
                        },
                        new
                        {
                            NodeId = 101,
                            Left = 295,
                            Name = "Node 101",
                            Right = 296
                        },
                        new
                        {
                            NodeId = 50,
                            Left = 290,
                            Name = "Node 50",
                            Right = 297
                        },
                        new
                        {
                            NodeId = 102,
                            Left = 299,
                            Name = "Node 102",
                            Right = 300
                        },
                        new
                        {
                            NodeId = 103,
                            Left = 301,
                            Name = "Node 103",
                            Right = 302
                        },
                        new
                        {
                            NodeId = 51,
                            Left = 298,
                            Name = "Node 51",
                            Right = 303
                        },
                        new
                        {
                            NodeId = 25,
                            Left = 289,
                            Name = "Node 25",
                            Right = 304
                        },
                        new
                        {
                            NodeId = 12,
                            Left = 258,
                            Name = "Node 12",
                            Right = 305
                        },
                        new
                        {
                            NodeId = 104,
                            Left = 309,
                            Name = "Node 104",
                            Right = 310
                        },
                        new
                        {
                            NodeId = 105,
                            Left = 311,
                            Name = "Node 105",
                            Right = 312
                        },
                        new
                        {
                            NodeId = 52,
                            Left = 308,
                            Name = "Node 52",
                            Right = 313
                        },
                        new
                        {
                            NodeId = 106,
                            Left = 315,
                            Name = "Node 106",
                            Right = 316
                        },
                        new
                        {
                            NodeId = 107,
                            Left = 317,
                            Name = "Node 107",
                            Right = 318
                        },
                        new
                        {
                            NodeId = 53,
                            Left = 314,
                            Name = "Node 53",
                            Right = 319
                        },
                        new
                        {
                            NodeId = 26,
                            Left = 307,
                            Name = "Node 26",
                            Right = 320
                        },
                        new
                        {
                            NodeId = 108,
                            Left = 323,
                            Name = "Node 108",
                            Right = 324
                        },
                        new
                        {
                            NodeId = 109,
                            Left = 325,
                            Name = "Node 109",
                            Right = 326
                        },
                        new
                        {
                            NodeId = 54,
                            Left = 322,
                            Name = "Node 54",
                            Right = 327
                        },
                        new
                        {
                            NodeId = 110,
                            Left = 329,
                            Name = "Node 110",
                            Right = 330
                        },
                        new
                        {
                            NodeId = 111,
                            Left = 331,
                            Name = "Node 111",
                            Right = 332
                        },
                        new
                        {
                            NodeId = 55,
                            Left = 328,
                            Name = "Node 55",
                            Right = 333
                        },
                        new
                        {
                            NodeId = 27,
                            Left = 321,
                            Name = "Node 27",
                            Right = 334
                        },
                        new
                        {
                            NodeId = 13,
                            Left = 306,
                            Name = "Node 13",
                            Right = 335
                        },
                        new
                        {
                            NodeId = 6,
                            Left = 257,
                            Name = "Node 6",
                            Right = 336
                        },
                        new
                        {
                            NodeId = 112,
                            Left = 341,
                            Name = "Node 112",
                            Right = 342
                        },
                        new
                        {
                            NodeId = 113,
                            Left = 343,
                            Name = "Node 113",
                            Right = 344
                        },
                        new
                        {
                            NodeId = 56,
                            Left = 340,
                            Name = "Node 56",
                            Right = 345
                        },
                        new
                        {
                            NodeId = 114,
                            Left = 347,
                            Name = "Node 114",
                            Right = 348
                        },
                        new
                        {
                            NodeId = 115,
                            Left = 349,
                            Name = "Node 115",
                            Right = 350
                        },
                        new
                        {
                            NodeId = 57,
                            Left = 346,
                            Name = "Node 57",
                            Right = 351
                        },
                        new
                        {
                            NodeId = 28,
                            Left = 339,
                            Name = "Node 28",
                            Right = 352
                        },
                        new
                        {
                            NodeId = 116,
                            Left = 355,
                            Name = "Node 116",
                            Right = 356
                        },
                        new
                        {
                            NodeId = 117,
                            Left = 357,
                            Name = "Node 117",
                            Right = 358
                        },
                        new
                        {
                            NodeId = 58,
                            Left = 354,
                            Name = "Node 58",
                            Right = 359
                        },
                        new
                        {
                            NodeId = 118,
                            Left = 361,
                            Name = "Node 118",
                            Right = 362
                        },
                        new
                        {
                            NodeId = 119,
                            Left = 363,
                            Name = "Node 119",
                            Right = 364
                        },
                        new
                        {
                            NodeId = 59,
                            Left = 360,
                            Name = "Node 59",
                            Right = 365
                        },
                        new
                        {
                            NodeId = 29,
                            Left = 353,
                            Name = "Node 29",
                            Right = 366
                        },
                        new
                        {
                            NodeId = 14,
                            Left = 338,
                            Name = "Node 14",
                            Right = 367
                        },
                        new
                        {
                            NodeId = 120,
                            Left = 371,
                            Name = "Node 120",
                            Right = 372
                        },
                        new
                        {
                            NodeId = 121,
                            Left = 373,
                            Name = "Node 121",
                            Right = 374
                        },
                        new
                        {
                            NodeId = 60,
                            Left = 370,
                            Name = "Node 60",
                            Right = 375
                        },
                        new
                        {
                            NodeId = 122,
                            Left = 377,
                            Name = "Node 122",
                            Right = 378
                        },
                        new
                        {
                            NodeId = 123,
                            Left = 379,
                            Name = "Node 123",
                            Right = 380
                        },
                        new
                        {
                            NodeId = 61,
                            Left = 376,
                            Name = "Node 61",
                            Right = 381
                        },
                        new
                        {
                            NodeId = 30,
                            Left = 369,
                            Name = "Node 30",
                            Right = 382
                        },
                        new
                        {
                            NodeId = 124,
                            Left = 385,
                            Name = "Node 124",
                            Right = 386
                        },
                        new
                        {
                            NodeId = 125,
                            Left = 387,
                            Name = "Node 125",
                            Right = 388
                        },
                        new
                        {
                            NodeId = 62,
                            Left = 384,
                            Name = "Node 62",
                            Right = 389
                        },
                        new
                        {
                            NodeId = 126,
                            Left = 391,
                            Name = "Node 126",
                            Right = 392
                        },
                        new
                        {
                            NodeId = 127,
                            Left = 393,
                            Name = "Node 127",
                            Right = 394
                        },
                        new
                        {
                            NodeId = 63,
                            Left = 390,
                            Name = "Node 63",
                            Right = 395
                        },
                        new
                        {
                            NodeId = 31,
                            Left = 383,
                            Name = "Node 31",
                            Right = 396
                        },
                        new
                        {
                            NodeId = 15,
                            Left = 368,
                            Name = "Node 15",
                            Right = 397
                        },
                        new
                        {
                            NodeId = 7,
                            Left = 337,
                            Name = "Node 7",
                            Right = 398
                        },
                        new
                        {
                            NodeId = 3,
                            Left = 256,
                            Name = "Node 3",
                            Right = 399
                        },
                        new
                        {
                            NodeId = 1,
                            Left = 1,
                            Name = "Node 1",
                            Right = 400
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
