// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParentChildAccess3.Data;

#nullable disable

namespace ParentChildAccess3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParentChildAccess3.Model.Node", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NodeId");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            NodeId = 1,
                            Name = "Node 1"
                        },
                        new
                        {
                            NodeId = 2,
                            Name = "Node 2"
                        },
                        new
                        {
                            NodeId = 3,
                            Name = "Node 3"
                        },
                        new
                        {
                            NodeId = 4,
                            Name = "Node 4"
                        },
                        new
                        {
                            NodeId = 5,
                            Name = "Node 5"
                        },
                        new
                        {
                            NodeId = 6,
                            Name = "Node 6"
                        },
                        new
                        {
                            NodeId = 7,
                            Name = "Node 7"
                        },
                        new
                        {
                            NodeId = 8,
                            Name = "Node 8"
                        },
                        new
                        {
                            NodeId = 9,
                            Name = "Node 9"
                        },
                        new
                        {
                            NodeId = 10,
                            Name = "Node 10"
                        },
                        new
                        {
                            NodeId = 11,
                            Name = "Node 11"
                        },
                        new
                        {
                            NodeId = 12,
                            Name = "Node 12"
                        },
                        new
                        {
                            NodeId = 13,
                            Name = "Node 13"
                        },
                        new
                        {
                            NodeId = 14,
                            Name = "Node 14"
                        },
                        new
                        {
                            NodeId = 15,
                            Name = "Node 15"
                        },
                        new
                        {
                            NodeId = 16,
                            Name = "Node 16"
                        },
                        new
                        {
                            NodeId = 17,
                            Name = "Node 17"
                        },
                        new
                        {
                            NodeId = 18,
                            Name = "Node 18"
                        },
                        new
                        {
                            NodeId = 19,
                            Name = "Node 19"
                        },
                        new
                        {
                            NodeId = 20,
                            Name = "Node 20"
                        });
                });

            modelBuilder.Entity("ParentChildAccess3.Model.NodeClosure", b =>
                {
                    b.Property<int>("AncestorId")
                        .HasColumnType("int");

                    b.Property<int>("DescendantId")
                        .HasColumnType("int");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("AncestorId", "DescendantId");

                    b.HasIndex("AncestorId");

                    b.HasIndex("DescendantId");

                    b.ToTable("NodeClosures");

                    b.HasData(
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 1,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 2,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 2,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 3,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 3,
                            DescendantId = 3,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 4,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 4,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 4,
                            DescendantId = 4,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 5,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 5,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 5,
                            DescendantId = 5,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 6,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 3,
                            DescendantId = 6,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 6,
                            DescendantId = 6,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 7,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 3,
                            DescendantId = 7,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 7,
                            DescendantId = 7,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 8,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 8,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 4,
                            DescendantId = 8,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 8,
                            DescendantId = 8,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 9,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 9,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 4,
                            DescendantId = 9,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 9,
                            DescendantId = 9,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 10,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 10,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 5,
                            DescendantId = 10,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 10,
                            DescendantId = 10,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 11,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 11,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 5,
                            DescendantId = 11,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 11,
                            DescendantId = 11,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 12,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 3,
                            DescendantId = 12,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 6,
                            DescendantId = 12,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 12,
                            DescendantId = 12,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 13,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 3,
                            DescendantId = 13,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 6,
                            DescendantId = 13,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 13,
                            DescendantId = 13,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 14,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 3,
                            DescendantId = 14,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 7,
                            DescendantId = 14,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 14,
                            DescendantId = 14,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 15,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 3,
                            DescendantId = 15,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 7,
                            DescendantId = 15,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 15,
                            DescendantId = 15,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 16,
                            Depth = 4
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 16,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 4,
                            DescendantId = 16,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 8,
                            DescendantId = 16,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 16,
                            DescendantId = 16,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 17,
                            Depth = 4
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 17,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 4,
                            DescendantId = 17,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 8,
                            DescendantId = 17,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 17,
                            DescendantId = 17,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 18,
                            Depth = 4
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 18,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 4,
                            DescendantId = 18,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 9,
                            DescendantId = 18,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 18,
                            DescendantId = 18,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 19,
                            Depth = 4
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 19,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 4,
                            DescendantId = 19,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 9,
                            DescendantId = 19,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 19,
                            DescendantId = 19,
                            Depth = 0
                        },
                        new
                        {
                            AncestorId = 1,
                            DescendantId = 20,
                            Depth = 4
                        },
                        new
                        {
                            AncestorId = 2,
                            DescendantId = 20,
                            Depth = 3
                        },
                        new
                        {
                            AncestorId = 5,
                            DescendantId = 20,
                            Depth = 2
                        },
                        new
                        {
                            AncestorId = 10,
                            DescendantId = 20,
                            Depth = 1
                        },
                        new
                        {
                            AncestorId = 20,
                            DescendantId = 20,
                            Depth = 0
                        });
                });

            modelBuilder.Entity("ParentChildAccess3.Model.NodeClosure", b =>
                {
                    b.HasOne("ParentChildAccess3.Model.Node", "Ancestor")
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParentChildAccess3.Model.Node", "Descendant")
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ancestor");

                    b.Navigation("Descendant");
                });
#pragma warning restore 612, 618
        }
    }
}
